production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>         # external host from Render
  port: <%= ENV['PGPORT'] || 5432 %>
  database: <%= ENV['PGDATABASE'] %> # database name from Render
  username: <%= ENV['PGUSERNAME'] %> # username from Render
  password: <%= ENV['PGPASSWORD'] %> # password from Render
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
